Module 2 Capstone Project
AbdimulhinYussuf3675/Module2_capstune_Project pull request #27
Opened 2023-02-10 14:28 UTC by Donmark2k

### Highlights 🥇

**Mnet Movie project**

**Learning objectives**

- Use webpack to bundle JavaScript.
- Use callbacks and promises.
- Learn how to use proper ES6 syntax.
- Use npm as software packages system.
- Use callbacks and promises.
- Use ES6 modules to write modular JavaScript.
- Send and receive data from an API.
- Use API documentation.
- Understand and use JSON.
- Make JavaScript code asynchronous.

**What I Have Done:**

- Added linters. The [JavaScript + HTML + CSS linter](https://github.com/microverseinc/linters-config/tree/master/html-css-js).
- I create a git flow.
- I create a webpack
- I used Es6 import.
- I send and receive data from an API.
- I make use of JavaScript code asynchronous.
- I add the count function

**Followed Rules:**

- Made sure [no linter errors](https://github.com/microverseinc/linters-config)
- Followed [Github Flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)
- Documented [professionaly](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)
- Followed the list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
- Followed our list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).

2023-02-10 16:33 UTC, OyePriscilla requested changes
Hi @Donmark2k, @AbdimulhinYussuf3675, @Tobby8629 👍, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425615-8927e377-c543-407b-8da4-5c09fecc261b.gif)

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-02-10 16:33 UTC, OyePriscilla commented on src/modules/addReserve.js
> +export default addReserve;
- [ ] Please kindly implement **async** and **await** with the fetch method to send and receive data from the API. The **async** and **await** keywords enable asynchronous, promise-based behavior to be written in a cleaner style. ℹ️ 

Kindly implement this for **addComment.js**, **fetchApiRes.js** and **fetchapi.js** modules as well (you may want to refactor your code easily as we have it in **addlikes.js**).

## Project requirement
![DSC_7491](https://user-images.githubusercontent.com/103386183/218141584-93002965-ef99-43eb-a162-1e6373612e6c.JPG)

2023-02-10 16:33 UTC, OyePriscilla commented on src/template.html
> +    </header>
- [ ] Can you please work more a bit on the typography of the header contents? The contrast between the text color and the background-color is too close, and I think the font-size supposed to be increased as well. 🙏

2023-02-10 16:38 UTC, OyePriscilla commented on README.md
> +> Describe the tech stack and include only the relevant sections that apply to your project. -->
- [ ] Please kindly remove all these templates from your README file in order to have a professional README file. 👍

2023-02-10 22:34 UTC, osamaashraf6 requested changes
Hi @Donmark2k 😊, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)


## Highlights💯🎈🪄✔️

- [x] Descriptive READme file in a professional way.✔️
- [x] No linter errors. ✔️
- [x] Good usage in correcting GitHub flow.✔️
- [x] Nice design.✔️


## Suggested changes


- Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-02-10 22:34 UTC, osamaashraf6 commented on src/modules/fetchApiRes.js
> +        return e;
- [ ] As stated 😃 by the previous reviewer kindly 😊 try to implement async and await with the fetch method to send and receive data from the API. The async and await keywords enable asynchronous, promise-based behavior to be written in a cleaner style.💯

2023-02-10 22:34 UTC, osamaashraf6 commented on src/modules/addcomment.js
> +    .then((resc) => resc.text());
- [ ] As stated 😃 by the previous reviewer kindly 😊 try to implement async and await with the fetch method to send and receive data from the API. The async and await keywords enable asynchronous, promise-based behavior to be written in a cleaner style.💯

2023-02-10 22:34 UTC, osamaashraf6 commented on src/modules/addReserve.js
> +    .then((resc) => resc.text());
- [ ] As stated 😃 by the previous reviewer kindly 😊 try to implement async and await with the fetch method to send and receive data from the API. The async and await keywords enable asynchronous, promise-based behavior to be written in a cleaner style.💯

2023-02-11 00:19 UTC, Felix45 approved these changes
# Approved :green_circle:  🎉  🎉  🎉 :clap:  :clap: 
Hi @AbdimulhinYussuf3675 & @Tobby8629

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉  🎉 🎉 🎉 

<img src="https://user-images.githubusercontent.com/58642949/216460900-e2b99a63-2f96-47cd-8829-ba141d96119a.gif" />

## Highlights :heavy_check_mark: 
- [ ] No linter errors :white_check_mark: 
- [ ] Repository has a professional readme file :white_check_mark: 
- [ ] Pull request has a descriptive title and summary :white_check_mark: 
- [ ] Implemented required changes from previous reviewer :white_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-11 00:27 UTC, merged

2023-02-11 00:28 UTC, Tobby8629 commented
Thank you 🙏🏾 !!!!

2023-02-11 09:37 UTC, OyePriscilla commented
@Donmark2k, @Tobby8629, and @AbdimulhinYussuf3675; Please kindly take note that you should have defined the involvement API once and import it to where it's needful. This will make your codebase DRY according to the best practices. ℹ️ 

> const baseApi = 'https://us-central1-involvement-api.cloudfunctions.net/capstoneApi/apps/'.

I'm so sorry for the late observation. 🙏

2023-02-11 15:36 UTC, AbdimulhinYussuf3675 commented
@OyePriscilla, Sure we will work on that. Thanks